# Generated by Django 5.1.5 on 2025-02-21 16:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Features",
            },
        ),
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#FF0000",  max_length=7
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Product Details",
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.ImageField(upload_to="")),
                (
                    "product_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.productdetails",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50, null=True)),
                (
                    "price_in_dollars",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=7
                    ),
                ),
                (
                    "gender_and_age",
                    models.CharField(
                        choices=[
                            ("W", "Women"),
                            ("M", "Men"),
                            ("U", "Unisex"),
                            ("G", "Girls"),
                            ("B", "Boys"),
                            ("K", "Kids"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField()),
                ("details", models.ManyToManyField(to="pages.productdetails")),
                ("feature", models.ManyToManyField(to="pages.features")),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Collections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("product", models.ManyToManyField(to="pages.products")),
            ],
            options={
                "verbose_name_plural": "Collections",
            },
        ),
    ]
