# Generated by Django 5.1.6 on 2025-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="size",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="content",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
