# Generated by Django 5.1.6 on 2025-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_productdetails_size_alter_productdetails_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="gender_and_age",
            field=models.CharField(
                choices=[
                    ("W", "Women"),
                    ("M", "Men"),
                    ("U", "Unisex"),
                    ("G", "Girls"),
                    ("B", "Boys"),
                    ("K", "Kids"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Collections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("product", models.ManyToManyField(to="pages.products")),
            ],
        ),
    ]
