# Generated by Django 5.1.6 on 2025-02-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_products_category_products_gender_and_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="price",
            new_name="price_in_dollars",
        ),
    ]
