# Generated by Django 5.1.6 on 2025-02-13 19:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_rename_price_products_price_in_dollars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
