# Generated by Django 5.1.7 on 2025-04-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_remove_productdetails_color_code_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="details",
        ),
        migrations.AddField(
            model_name="productdetails",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.products",
            ),
            preserve_default=False,
        ),
    ]
