# Generated by Django 5.1.6 on 2025-02-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_productdetails_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="pages.products",
            ),
        ),
    ]
