# Generated by Django 5.1.6 on 2025-02-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_productdetails_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productdetails",
            old_name="color",
            new_name="color_code",
        ),
    ]
