# Generated by Django 5.1.5 on 2025-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_rename_color_productdetails_color_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collections",
            options={"verbose_name_plural": "Collections"},
        ),
        migrations.AlterModelOptions(
            name="features",
            options={"verbose_name_plural": "Features"},
        ),
        migrations.AlterModelOptions(
            name="productdetails",
            options={"verbose_name_plural": "Product Details"},
        ),
        migrations.AlterModelOptions(
            name="productimages",
            options={"verbose_name_plural": "Product Images"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AddField(
            model_name="products",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD $"),
                    ("EUR", "EUR €"),
                    ("TRY", "TL ₺"),
                    ("GBP", "GBP £"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
