# Generated by Django 5.1.5 on 2025-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_collections_options_alter_features_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetails",
            name="product",
        ),
        migrations.AddField(
            model_name="products",
            name="details",
            field=models.ManyToManyField(to="pages.productdetails"),
        ),
    ]
